### PR TITLE
Draft: react-native-sentry Merge Upstream

### PR DESCRIPTION
**Pull request by colincarter**
PR to bring react-native-upstream up-to-date with the upstream version which works round an issue with npm >6.4 on windows.  During a checkout npm will do a `git submodule update --init --recursive` and there is an error `failed to recurse into ios\Sentry\KSCrash`.  The upstream has removed the KSCrash git submodule dependency.

Beyond verifying this fixes the npm issue it hasn't been tested in an app.  Testing advice would be welcome.

### CODE REVIEW

**Comment by charlie-axsy** [comment]
@colincarter I experienced running `npm install` inside react-app/SF was failing for me because it was depending on this branch - see https://github.com/axsy-dev/react-app/blob/master/SF/package.json#L88.  

What do you recommend as the version for the `react-native-sentry` dep for SF?  I restored the branch to unblock me in the short term.  I guess it must be cached on the CI build but may break in the future.

**Comment by colincarter** [comment]
@charlie-axsy What is your use case for `npm install`'ing in the SF folder?  We don't have to install in that directory anymore.  I think given the work Gill did on Sentry this branch is no longer needed.

**Comment by charlie-axsy** [comment]
@colincarter I ran `npm install` in SF to regenerate package-lock in a branch of mine in order to resolve dozens of merge conflicts.    

Can SF/package.json be removed?

**Comment by colincarter** [comment]
@charlie-axsy I would opt for keeping it.  There are some tests (although they don't work) which run from the SF folder.  Also the `package.json` would come in handy if we split the SF folder out into an npm module.

**Comment by stephen-peck** [comment]
Yeah let's keep package.json for now, I'd like to pick up some work I did on making AxsyApp and SF standalone modules so we can manage their dependencies and refactor more easily.

We shouldn't be updating package-lock.json though

**Comment by charlie-axsy** [comment]
@stephen-peck 

> We shouldn't be updating package-lock.json though

It seems unfeasible to try and manually merge a package-lock file, and there will be merge conflicts in the case where a branch and master have both added new dependencies since the last fork/rebase.  You're right that updating package-lock should be an operation used sparingly, but is there another way in this scenario?

Edit: thinking about this more - surely in any scenario where a branch adds a new dep there will be always be an update to package-lock.  I'm not sure if there is an easy way to generate a new lock without touching the deps across the entire app and potentially bumping deps unrelated to the one added

If I notice a merge conflict in package-lock.json I resolve it by running:

```
git checkout origin/master package-lock.json
npm i
```

**Comment by stephen-peck** [comment]
@charlie-axsy I only meant in this specific circumstance, where the SF package.json is considerably out of date, and not in live use, updating package.lock.json isn't really adding value but is adding to confusion (implying it - and hence SF as a standalone package - are actively maintained)

There's a draft PR to bring SF and AxsyApp back up to date, first as lintable and flow checkable and then as standalone modules prior to refactoring into something smaller https://github.com/axsy-dev/react-app/pull/2215

**Pull request closed without merging**
